# Generated by Django 4.2.16 on 2026-06-22 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepositProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fin_co_no', models.CharField(max_length=20)),
                ('fin_prdt_cd', models.CharField(max_length=50)),
                ('kor_co_nm', models.CharField(max_length=100)),
                ('fin_prdt_nm', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=10)),
                ('join_way', models.CharField(blank=True, max_length=500)),
                ('mtrt_int', models.TextField(blank=True)),
                ('spcl_cnd', models.TextField(blank=True)),
                ('join_deny', models.CharField(blank=True, max_length=30)),
                ('join_member', models.TextField(blank=True)),
                ('etc_note', models.TextField(blank=True)),
                ('max_limit', models.TextField(blank=True)),
                ('dcls_month', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['kor_co_nm', 'fin_prdt_nm'],
                'unique_together': {('fin_co_no', 'fin_prdt_cd')},
            },
        ),
        migrations.CreateModel(
            name='DepositOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intr_rate_type', models.CharField(max_length=5)),
                ('intr_rate_type_nm', models.CharField(max_length=20)),
                ('save_trm', models.IntegerField()),
                ('intr_rate', models.FloatField(default=0)),
                ('intr_rate2', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='deposits.depositproduct')),
            ],
            options={
                'ordering': ['save_trm', 'intr_rate_type'],
                'unique_together': {('product', 'save_trm', 'intr_rate_type')},
            },
        ),
    ]
