# Generated by Django 4.2.16 on 2026-06-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0002_alter_depositproduct_product_type_saveddeposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saveddeposit',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='saveddeposit',
            name='final_rate',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='depositproduct',
            unique_together={('fin_co_no', 'fin_prdt_cd', 'product_type')},
        ),
    ]
