# Generated by Django 4.2.16 on 2026-06-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_survey_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
