# Generated by Django 4.2.16 on 2026-06-24 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_last_survey_date'),
        ('accounts', '0002_user_profile_image'),
    ]

    operations = [
    ]
