# Generated by Django 4.2.16 on 2026-06-21 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("category", models.CharField(max_length=30)),
                ("price", models.PositiveIntegerField(default=0)),
                ("change", models.FloatField(default=0.0)),
                ("suitable_types", models.JSONField(default=list)),
            ],
        ),
    ]
