# Generated by Django 4.2.16 on 2026-06-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="market",
            field=models.CharField(default="KOSPI", max_length=10),
        ),
        migrations.AlterField(
            model_name="stock",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
