# Generated by Django 4.2.16 on 2026-06-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_stock_market_alter_stock_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="market_cap",
            field=models.BigIntegerField(default=0),
        ),
    ]
