# Generated by Django 4.2.16 on 2026-06-23 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_stock_market_cap'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFinancials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('per', models.FloatField(null=True)),
                ('pbr', models.FloatField(null=True)),
                ('roe', models.FloatField(null=True)),
                ('debt_ratio', models.FloatField(null=True)),
                ('current_ratio', models.FloatField(null=True)),
                ('op_margin', models.FloatField(null=True)),
                ('risk_score', models.FloatField(null=True)),
                ('updated_at', models.DateField(null=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock')),
            ],
        ),
    ]
