# Generated by Django 4.2.16 on 2026-06-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stockfinancials'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfinancials',
            name='health_score',
            field=models.FloatField(null=True),
        ),
    ]
